### ISSUE TITLE
Roadmap: Versão Alpha

### ISSUE THREAD

**Issue by pedropapa** [brazucas/samp-server#3]
## Core
- [x] Base de dados
- [x] Migrations
- [x] #4
- [x] Registro
- [x] Autenticação
- [x] Voip (https://github.com/CyberMor/sampvoice)
- [x] Sistema marcar como AFK
- [ ] Moderação
  - [ ] Kick
  - [ ] Ban
  - [ ] Mute Voice
  - [ ] Mute Chat
- [ ] Sistema de UI
  - [ ] Desktop: [CEF](https://github.com/Pycckue-Bnepeg/samp-cef/blob/master/docs/main_en.md)
  - [ ] Desktop: Textdraws/Dialogs
  - [ ] Android: Dialogs

## RPG
- [ ] Tela de início
- [ ] Criação de personagem
- [ ] Sistema de Spawn
  - [ ] Hotel'BRZ
- [ ] Inventário
- [x] HUD
- [ ] Profissão: Taxista
- [ ] Profissão: Pizza delivery
- [ ] Profissão: Policial
- [ ] Profissão: Agricultor
  - [ ] Plantação de maconha

## Minigames
- [ ] Sistema de spawn
- [ ] Sistema de seleção de Minigame
  - Baseado em jogadores online
- [ ] Minigame: Car Derby (Naufragos?)
- [ ] Minigame: Race (Nascar?)
- [ ] Minigame: Team Deathmatch (Chinatown Wars)
- [ ] Minigame: Team Deathmatch w/ Leader (Mafia)
- [ ] Minigame: Deathmatch (Snipers)
- [ ] Minigame: Timed Deathmatch (Assassinos)
